name: 'Create release'
description: 'Create releases for tags'

runs:
  using: "composite"
  steps:
    - name: Set Tag Name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      # trim prefix from ref to get tag name
      run: echo "TAG_NAME=${GITHUB_REF#'refs/tags/'}" >> ${GITHUB_ENV}

    - name: Add tag to folder name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv ${{ env.ZIP_NAME }} ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: 'zip'
        path: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}
        filename: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        subject-path: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip

    - name: Release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip
