name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # Common Linux dependencies
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build
        # https://github.com/llvm/llvm-project/issues/78354
        sudo sysctl vm.mmap_rnd_bits=28

    # Also see https://github.com/actions/runner-images/discussions/9446#discussioncomment-8668538
    - name: Install Clang ${{ matrix.clang_ver }}
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_msan == true
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh ${{ matrix.clang_ver }}

    - name: Install libc++ (Linux Clang ${{ matrix.clang_ver }})
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_msan == true
      run: |
        # sudo apt-get update
        sudo apt-get install --no-install-recommends libc++-${{ matrix.clang_ver }}-dev libc++abi-${{ matrix.clang_ver }}-dev

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        # sudo apt-get update
        sudo apt-get install --no-install-recommends valgrind
